import = ["~/.dotfiles/alacritty/themes/tokyonight.toml"]
live_config_reload = true

[window]
dynamic_padding = true
decorations = "Full"
opacity = 0.9
blur = true

[window.padding]
x = 6
y = 6

[font]
size = 14.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[cursor.style]
blinking = "Always"
shape = "Underline"
