#!/usr/bin/env sh

# load scripting addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    layout                       bsp            \
    auto_balance                 on             \
    window_placement             seccond_child  \
    window_shadow                float          \
    window_topmost               off            \
    window_opacity               off            \
    window_border                off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   6              \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# disable specific apps
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Hidden Bar$" manage=off
yabai -m rule --add app="^Keyboard Setup Assistant" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Safari$" title="(General|Tabs|Autofill|Passwords|Search|Security|Privacy|Websites|Profiles|Extensions|Advanced|Developer|Feature Flags)" manage=off
yabai -m rule --add app="^Script Console$" manage=off
yabai -m rule --add app="^Spaceman$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^IINA" manage=off
